services:
  - type: web
    name: netlife-atc-detector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_API_KEY
        sync: false
      - key: DB_HOST
        value: dpg-d5l6jvh4tr6s738gfr60-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: bddgeneral
      - key: DB_USER
        value: bdd_admin
      - key: DB_PASSWORD
        sync: false
      - key: NOVONET_BITRIX
        value: https://novonet.bitrix24.es/rest/87387/vcca209sfcjflxp8
      - key: NOVONET_ATC_STAGE
        value: C19:UC_U0JYD8
      - key: NOVONET_WAZZUP_KEY
        sync: false
      - key: VENSA_BITRIX
        value: https://aclopecuador.bitrix24.es/rest/1/49hra49433psie0t
      - key: VENSA_ATC_STAGE
        value: ""
      - key: VENSA_WAZZUP_KEY
        sync: false
